import { TaskTypes } from "@dipmaxtech/clr-pkg";

type TaskKeys =
  | "DEALS_ON_EBY"
  | "DEALS_ON_AZN"
  | "DAILY_SALES"
  | "CRAWL_SHOP"
  | "WHOLESALE_SEARCH"
  | "WHOLESALE_EBY_SEARCH"
  | "SCAN_SHOP"
  | "MATCH_PRODUCTS"
  | "NEG_AZN_DEALS"
  | "NEG_EBY_DEALS"
  | "CRAWL_EAN"
  | "LOOKUP_INFO"
  | "QUERY_EANS_EBY"
  | "LOOKUP_CATEGORY";

export type MultiStageTaskTypes = "WHOLESALE_EBY_SEARCH" | "WHOLESALE_SEARCH";

export const TASK_TYPES: { [key in TaskKeys]: TaskTypes } = {
  DEALS_ON_EBY: "DEALS_ON_EBY",
  DEALS_ON_AZN: "DEALS_ON_AZN",
  WHOLESALE_EBY_SEARCH: "WHOLESALE_EBY_SEARCH",
  NEG_AZN_DEALS: "CRAWL_AZN_LISTINGS",
  NEG_EBY_DEALS: "CRAWL_EBY_LISTINGS",
  DAILY_SALES: "DAILY_SALES",
  CRAWL_SHOP: "CRAWL_SHOP",
  WHOLESALE_SEARCH: "WHOLESALE_SEARCH",
  SCAN_SHOP: "SCAN_SHOP",
  MATCH_PRODUCTS: "MATCH_PRODUCTS",
  CRAWL_EAN: "CRAWL_EAN",
  LOOKUP_INFO: "LOOKUP_INFO",
  QUERY_EANS_EBY: "QUERY_EANS_EBY",
  LOOKUP_CATEGORY: "LOOKUP_CATEGORY",
};

export type MultiShopTaskTypes =
  | "DEALS_ON_AZN"
  | "NEG_AZN_DEALS"
  | "DEALS_ON_EBY"
  | "NEG_EBY_DEALS"
  | "CRAWL_EAN"
  | "LOOKUP_INFO"
  | "QUERY_EANS_EBY"
  | "LOOKUP_CATEGORY";

export type MultiShopTaskProgressQueries =
  | "DEALS_ON_AZN"
  | "NEG_AZN_DEALS"
  | "CRAWL_EAN"
  | "LOOKUP_INFO"
  | "QUERY_EANS_EBY"
  | "LOOKUP_CATEGORY";

export type MultiShopTaskProgressQueriesAgg =
  | "DEALS_ON_EBY"
  | "NEG_EBY_DEALS"

export const MULTI_SHOP_TASKS: {
  [key in MultiShopTaskTypes]: MultiShopTaskTypes;
} = {
  CRAWL_EAN: "CRAWL_EAN",
  LOOKUP_INFO: "LOOKUP_INFO",
  QUERY_EANS_EBY: "QUERY_EANS_EBY",
  LOOKUP_CATEGORY: "LOOKUP_CATEGORY",
  DEALS_ON_EBY: "DEALS_ON_EBY",
  DEALS_ON_AZN: "DEALS_ON_AZN",
  NEG_AZN_DEALS: "NEG_AZN_DEALS",
  NEG_EBY_DEALS: "NEG_EBY_DEALS",
};
