import { describe, expect, test } from "@jest/globals";
//@ts-ignore
import { transformProduct } from "../../src/util/transformProduct.js";
describe("Transform Product", () => {
  const oldProduct = {
    _id: {
      $oid: "66882c3a34bbb31de7f8dd57",
    },
    link: "https://www.cyberport.de/apple-und-zubehoer/apple-homepod/apple/pdp/5s0a-006/apple-homepod-mini-weiss.html",
    image:
      "https://im.cyberport.de/is/image/cyberport/211111135326900301900002K?$Zoom_500$ 2x",
    shop: "cyberport.de",
    category: ["Apple", "Apple"],
    name: "Apple HomePod mini weiß",
    vendor: "",
    mnfctr: "",
    hasMnfctr: false,
    price: 105,
    promoPrice: 95,
    prime: false,
    description: "ddddddd",
    nameSub: "ddddd",
    s_hash: "bcf95febb364075822fe8bea9b57ffc9",
    createdAt: "2024-07-05T17:24:10.682Z",
    updatedAt: "2024-08-16T00:02:58.032Z",
    locked: false,
    taskId: "",
    asin: "B09FF8KY2Q",
    candidates: {
      "amazon.de": [
        {
          vendor: "",
          nm: "Balolo Tripod | Apple HomePod Mini Halterung Ständer | Weiß",
          lnk: "https://www.amazon.de/sspa/click?ie=UTF8&spc=MTozMzc0ODcwMjc0MDk0ODI6MTcyMDIwNTYwNTpzcF9hdGY6MjAwNDYzMjI3MDE0OTg6OjA6Og&url=%2FBalolo-Tripod-HomePod-Halterung-St%25C3%25A4nder%2Fdp%2FB09FF8KY2Q%2Fref%3Dsr_1_1_sspa%3Fdib%3DeyJ2IjoiMSJ9.VjLK3DMcuCEYU8s7zYbKwwNMp4f8d1D8BjReFd2no6xpqCQimATUUBE8uoqm6rY9yXYAxQQFFTMj2b6tN10R4g3SGOaAaQ88KgbBJc2ikfffPs3Qu4JFeHh-KInheyvLZias_OL3zHMkwLqKuusDnUc0u5PSgZ-u991IGlNJ-A2a5DwsdJlnMh_6DHogpmppkE6YlvXY0okiIaFTfEey47JfkDCquFkFw7O1Xsla2Ms.J1VDzBDZeK9hmlu6-ckC7hkb19fL9LMO1CDPup8P9RE%26dib_tag%3Dse%26keywords%3DApple%2BHomePod%2Bmini%2Bwei%25C3%259F%26qid%3D1720205605%26sr%3D8-1-spons%26sp_csd%3Dd2lkZ2V0TmFtZT1zcF9hdGY%26psc%3D1",
          nmSegments: [
            "balolo",
            "tripod",
            "|",
            "apple",
            "homepod",
            "mini",
            "halterung",
            "ständer",
            "|",
            "weiß",
          ],
          prc: 20.92,
        },
        {
          vendor: "",
          nm: "Balolo Tripod | Apple HomePod Mini Halterung Ständer | Weiß",
          lnk: "https://www.amazon.de/Balolo-Tripod-HomePod-Halterung-St%C3%A4nder/dp/B09FF8KY2Q/ref=sr_1_2?dib=eyJ2IjoiMSJ9.VjLK3DMcuCEYU8s7zYbKwwNMp4f8d1D8BjReFd2no6xpqCQimATUUBE8uoqm6rY9yXYAxQQFFTMj2b6tN10R4g3SGOaAaQ88KgbBJc2ikfffPs3Qu4JFeHh-KInheyvLZias_OL3zHMkwLqKuusDnUc0u5PSgZ-u991IGlNJ-A2a5DwsdJlnMh_6DHogpmppkE6YlvXY0okiIaFTfEey47JfkDCquFkFw7O1Xsla2Ms.J1VDzBDZeK9hmlu6-ckC7hkb19fL9LMO1CDPup8P9RE&dib_tag=se&keywords=Apple+HomePod+mini+wei%C3%9F&qid=1720205605&sr=8-2",
          nmSegments: [
            "balolo",
            "tripod",
            "|",
            "apple",
            "homepod",
            "mini",
            "halterung",
            "ständer",
            "|",
            "weiß",
          ],
          prc: 20.92,
        },
        {
          vendor: "",
          nm: "Generisch Designkarussell Halterung für HomePod Mini (weiß/rund), schraubenlose Wandhalterung für die Steckdose, Stabiler Wandhalter mit Kabelmanagement…",
          lnk: "https://www.amazon.de/Generisch-Designkarussell-schraubenlose-Wandhalterung-Kabelmanagement/dp/B0BGJHXVQF/ref=sr_1_3?dib=eyJ2IjoiMSJ9.VjLK3DMcuCEYU8s7zYbKwwNMp4f8d1D8BjReFd2no6xpqCQimATUUBE8uoqm6rY9yXYAxQQFFTMj2b6tN10R4g3SGOaAaQ88KgbBJc2ikfffPs3Qu4JFeHh-KInheyvLZias_OL3zHMkwLqKuusDnUc0u5PSgZ-u991IGlNJ-A2a5DwsdJlnMh_6DHogpmppkE6YlvXY0okiIaFTfEey47JfkDCquFkFw7O1Xsla2Ms.J1VDzBDZeK9hmlu6-ckC7hkb19fL9LMO1CDPup8P9RE&dib_tag=se&keywords=Apple+HomePod+mini+wei%C3%9F&qid=1720205605&sr=8-3",
          nmSegments: [
            "generisch",
            "designkarussell",
            "halterung",
            "für",
            "homepod",
            "mini",
            "(weiß",
            "rund)",
            "schraubenlose",
            "wandhalterung",
            "für",
            "die",
            "steckdose",
            "stabiler",
            "wandhalter",
            "mit",
            "kabelmanagement…",
          ],
          prc: 25.2,
        },
        {
          vendor: "",
          nm: "Wandhalterung Kompatibel mit Homepod Mini – Halterung Geeignet für Verschiedene Wandtypen, Kabelmanagement und Platzsparendes Design, Stabiler Wandständer für Schlafzimmer und Küche (Weiß)",
          lnk: "https://www.amazon.de/Wandhalterung-Kompatibel-Homepod-Mini-Kabelmanagement/dp/B09MCV6V1F/ref=sr_1_4?dib=eyJ2IjoiMSJ9.VjLK3DMcuCEYU8s7zYbKwwNMp4f8d1D8BjReFd2no6xpqCQimATUUBE8uoqm6rY9yXYAxQQFFTMj2b6tN10R4g3SGOaAaQ88KgbBJc2ikfffPs3Qu4JFeHh-KInheyvLZias_OL3zHMkwLqKuusDnUc0u5PSgZ-u991IGlNJ-A2a5DwsdJlnMh_6DHogpmppkE6YlvXY0okiIaFTfEey47JfkDCquFkFw7O1Xsla2Ms.J1VDzBDZeK9hmlu6-ckC7hkb19fL9LMO1CDPup8P9RE&dib_tag=se&keywords=Apple+HomePod+mini+wei%C3%9F&qid=1720205605&sr=8-4",
          nmSegments: [
            "wandhalterung",
            "kompatibel",
            "mit",
            "homepod",
            "mini",
            "–",
            "halterung",
            "geeignet",
            "für",
            "verschiedene",
            "wandtypen",
            "kabelmanagement",
            "und",
            "platzsparendes",
            "design",
            "stabiler",
            "wandständer",
            "für",
            "schlafzimmer",
            "und",
            "küche",
            "(weiß)",
          ],
          prc: 10.92,
        },
        {
          vendor: "",
          nm: "PlusAcc Akku Kompatibel mit HomePod Mini - Batterie Ständer Home Pod Mini Zubehör Akkustation mit integriertem Kabelmanagement (Ohne Geräte) Weiß",
          lnk: "https://www.amazon.de/PlusAcc-Akku-Kompatibel-HomePod-Mini/dp/B0C539B85N/ref=sr_1_5?dib=eyJ2IjoiMSJ9.VjLK3DMcuCEYU8s7zYbKwwNMp4f8d1D8BjReFd2no6xpqCQimATUUBE8uoqm6rY9yXYAxQQFFTMj2b6tN10R4g3SGOaAaQ88KgbBJc2ikfffPs3Qu4JFeHh-KInheyvLZias_OL3zHMkwLqKuusDnUc0u5PSgZ-u991IGlNJ-A2a5DwsdJlnMh_6DHogpmppkE6YlvXY0okiIaFTfEey47JfkDCquFkFw7O1Xsla2Ms.J1VDzBDZeK9hmlu6-ckC7hkb19fL9LMO1CDPup8P9RE&dib_tag=se&keywords=Apple+HomePod+mini+wei%C3%9F&qid=1720205605&sr=8-5",
          nmSegments: [
            "plusacc",
            "akku",
            "kompatibel",
            "mit",
            "homepod",
            "mini",
            "batterie",
            "ständer",
            "home",
            "pod",
            "mini",
            "zubehör",
            "akkustation",
            "mit",
            "integriertem",
            "kabelmanagement",
            "(ohne",
            "geräte)",
            "weiß",
          ],
          prc: 45.37,
        },
        {
          vendor: "",
          nm: "Aokicase Kompatibel mit Apple HomePod Mini Halter Wandhalterung Ständer Halterung Zubehör mit integriertem Kabelmanagement,Lautsprecher Zubehör Rack(Apple HomePod Mini,Weiß) 2 PCS",
          lnk: "https://www.amazon.de/Kompatibel-Wandhalterung-integriertem-Kabelmanagement-Lautsprecher/dp/B0B24YNRJ9/ref=sr_1_6?dib=eyJ2IjoiMSJ9.VjLK3DMcuCEYU8s7zYbKwwNMp4f8d1D8BjReFd2no6xpqCQimATUUBE8uoqm6rY9yXYAxQQFFTMj2b6tN10R4g3SGOaAaQ88KgbBJc2ikfffPs3Qu4JFeHh-KInheyvLZias_OL3zHMkwLqKuusDnUc0u5PSgZ-u991IGlNJ-A2a5DwsdJlnMh_6DHogpmppkE6YlvXY0okiIaFTfEey47JfkDCquFkFw7O1Xsla2Ms.J1VDzBDZeK9hmlu6-ckC7hkb19fL9LMO1CDPup8P9RE&dib_tag=se&keywords=Apple+HomePod+mini+wei%C3%9F&qid=1720205605&sr=8-6",
          nmSegments: [
            "aokicase",
            "kompatibel",
            "mit",
            "apple",
            "homepod",
            "mini",
            "halter",
            "wandhalterung",
            "ständer",
            "halterung",
            "zubehör",
            "mit",
            "integriertem",
            "kabelmanagement",
            "lautsprecher",
            "zubehör",
            "rack(apple",
            "homepod",
            "mini",
            "weiß)",
            "2",
            "pcs",
          ],
          prc: 17.64,
        },
        {
          vendor: "",
          nm: "AHASTYLE HomePod Mini Wandhalterung ABS Ständerhalter mit Kabel Verwaltung- Accessories für Apple HomePod Mini mit Schrauben Platzsparende für Küche, Bad und Schlafzimmer (Weiß)",
          lnk: "https://www.amazon.de/sspa/click?ie=UTF8&spc=MTozMzc0ODcwMjc0MDk0ODI6MTcyMDIwNTYwNTpzcF9tdGY6MjAwOTMyNjkxOTk2MDY6OjA6Og&url=%2FAHASTYLE-Wandhalterung-St%25C3%25A4nderhalter-Platzsparende-Schlafzimmer%2Fdp%2FB096XSJJYG%2Fref%3Dsr_1_7_sspa%3Fdib%3DeyJ2IjoiMSJ9.VjLK3DMcuCEYU8s7zYbKwwNMp4f8d1D8BjReFd2no6xpqCQimATUUBE8uoqm6rY9yXYAxQQFFTMj2b6tN10R4g3SGOaAaQ88KgbBJc2ikfffPs3Qu4JFeHh-KInheyvLZias_OL3zHMkwLqKuusDnUc0u5PSgZ-u991IGlNJ-A2a5DwsdJlnMh_6DHogpmppkE6YlvXY0okiIaFTfEey47JfkDCquFkFw7O1Xsla2Ms.J1VDzBDZeK9hmlu6-ckC7hkb19fL9LMO1CDPup8P9RE%26dib_tag%3Dse%26keywords%3DApple%2BHomePod%2Bmini%2Bwei%25C3%259F%26qid%3D1720205605%26sr%3D8-7-spons%26sp_csd%3Dd2lkZ2V0TmFtZT1zcF9tdGY%26psc%3D1",
          nmSegments: [
            "ahastyle",
            "homepod",
            "mini",
            "wandhalterung",
            "abs",
            "ständerhalter",
            "mit",
            "kabel",
            "verwaltung",
            "accessories",
            "für",
            "apple",
            "homepod",
            "mini",
            "mit",
            "schrauben",
            "platzsparende",
            "für",
            "küche",
            "bad",
            "und",
            "schlafzimmer",
            "(weiß)",
          ],
          prc: 7.55,
        },
        {
          vendor: "",
          nm: "HUAYUWA Weiße runde Wandhalterung, Audioständer, kompatibel mit Homepod Mini Smart Audio mit integriertem Kabelmanagement",
          lnk: "https://www.amazon.de/HUAYUWA-Wandhalterung-Audiost%C3%A4nder-integriertem-Kabelmanagement/dp/B0C5CW772J/ref=sr_1_8?dib=eyJ2IjoiMSJ9.VjLK3DMcuCEYU8s7zYbKwwNMp4f8d1D8BjReFd2no6xpqCQimATUUBE8uoqm6rY9yXYAxQQFFTMj2b6tN10R4g3SGOaAaQ88KgbBJc2ikfffPs3Qu4JFeHh-KInheyvLZias_OL3zHMkwLqKuusDnUc0u5PSgZ-u991IGlNJ-A2a5DwsdJlnMh_6DHogpmppkE6YlvXY0okiIaFTfEey47JfkDCquFkFw7O1Xsla2Ms.J1VDzBDZeK9hmlu6-ckC7hkb19fL9LMO1CDPup8P9RE&dib_tag=se&keywords=Apple+HomePod+mini+wei%C3%9F&qid=1720205605&sr=8-8",
          nmSegments: [
            "huayuwa",
            "weiße",
            "runde",
            "wandhalterung",
            "audioständer",
            "kompatibel",
            "mit",
            "homepod",
            "mini",
            "smart",
            "audio",
            "mit",
            "integriertem",
            "kabelmanagement",
          ],
          prc: 12.6,
        },
        {
          vendor: "",
          nm: "AHASTYLE HomePod Mini Wandhalterung ABS Ständerhalter mit Kabel Verwaltung- Accessories für Apple HomePod Mini mit Schrauben Platzsparende für Küche, Bad und Schlafzimmer (Weiß_2 Stück)",
          lnk: "https://www.amazon.de/AHASTYLE-Wandhalterung-St%C3%A4nderhalter-Platzsparende-Schlafzimmer/dp/B096XSQK5P/ref=sr_1_9?dib=eyJ2IjoiMSJ9.VjLK3DMcuCEYU8s7zYbKwwNMp4f8d1D8BjReFd2no6xpqCQimATUUBE8uoqm6rY9yXYAxQQFFTMj2b6tN10R4g3SGOaAaQ88KgbBJc2ikfffPs3Qu4JFeHh-KInheyvLZias_OL3zHMkwLqKuusDnUc0u5PSgZ-u991IGlNJ-A2a5DwsdJlnMh_6DHogpmppkE6YlvXY0okiIaFTfEey47JfkDCquFkFw7O1Xsla2Ms.J1VDzBDZeK9hmlu6-ckC7hkb19fL9LMO1CDPup8P9RE&dib_tag=se&keywords=Apple+HomePod+mini+wei%C3%9F&qid=1720205605&sr=8-9",
          nmSegments: [
            "ahastyle",
            "homepod",
            "mini",
            "wandhalterung",
            "abs",
            "ständerhalter",
            "mit",
            "kabel",
            "verwaltung",
            "accessories",
            "für",
            "apple",
            "homepod",
            "mini",
            "mit",
            "schrauben",
            "platzsparende",
            "für",
            "küche",
            "bad",
            "und",
            "schlafzimmer",
            "(weiß_2",
            "stück)",
          ],
          prc: 9.24,
        },
        {
          vendor: "",
          nm: "Generisch Designkarussell Halterung für HomePod Mini (Weiß), schraubenlose Wandhalterung für die Steckdose, Stabiler Wandhalter mit Kabelmanagement",
          lnk: "https://www.amazon.de/Designkarussell-schraubenlose-Wandhalterung-Wandhalter-Kabelmanagement/dp/B0B25NKLS7/ref=sr_1_10?dib=eyJ2IjoiMSJ9.VjLK3DMcuCEYU8s7zYbKwwNMp4f8d1D8BjReFd2no6xpqCQimATUUBE8uoqm6rY9yXYAxQQFFTMj2b6tN10R4g3SGOaAaQ88KgbBJc2ikfffPs3Qu4JFeHh-KInheyvLZias_OL3zHMkwLqKuusDnUc0u5PSgZ-u991IGlNJ-A2a5DwsdJlnMh_6DHogpmppkE6YlvXY0okiIaFTfEey47JfkDCquFkFw7O1Xsla2Ms.J1VDzBDZeK9hmlu6-ckC7hkb19fL9LMO1CDPup8P9RE&dib_tag=se&keywords=Apple+HomePod+mini+wei%C3%9F&qid=1720205605&sr=8-10",
          nmSegments: [
            "generisch",
            "designkarussell",
            "halterung",
            "für",
            "homepod",
            "mini",
            "(weiß)",
            "schraubenlose",
            "wandhalterung",
            "für",
            "die",
            "steckdose",
            "stabiler",
            "wandhalter",
            "mit",
            "kabelmanagement",
          ],
          prc: 25.2,
        },
        {
          vendor: "",
          nm: "Molitececool Wandhalter für Homepod Mini, stabile Lautsprecher-Wandhalterung für Homepod Mini, platzsparend, exzellentes Kabelmanagement ohne Kabelsalat (White)",
          lnk: "https://www.amazon.de/Molitececool-Lautsprecher-Wandhalterung-platzsparend-exzellentes-Kabelmanagement/dp/B092DDH1M2/ref=sr_1_11?dib=eyJ2IjoiMSJ9.VjLK3DMcuCEYU8s7zYbKwwNMp4f8d1D8BjReFd2no6xpqCQimATUUBE8uoqm6rY9yXYAxQQFFTMj2b6tN10R4g3SGOaAaQ88KgbBJc2ikfffPs3Qu4JFeHh-KInheyvLZias_OL3zHMkwLqKuusDnUc0u5PSgZ-u991IGlNJ-A2a5DwsdJlnMh_6DHogpmppkE6YlvXY0okiIaFTfEey47JfkDCquFkFw7O1Xsla2Ms.J1VDzBDZeK9hmlu6-ckC7hkb19fL9LMO1CDPup8P9RE&dib_tag=se&keywords=Apple+HomePod+mini+wei%C3%9F&qid=1720205605&sr=8-11",
          nmSegments: [
            "molitececool",
            "wandhalter",
            "für",
            "homepod",
            "mini",
            "stabile",
            "lautsprecher",
            "wandhalterung",
            "für",
            "homepod",
            "mini",
            "platzsparend",
            "exzellentes",
            "kabelmanagement",
            "ohne",
            "kabelsalat",
            "(white)",
          ],
          prc: 8.06,
        },
        {
          vendor: "",
          nm: "Splin Deckenhalterung für den Einbau, kompatibel mit Smart-Lautsprechern Alexa Echo Dot 4. und 5. Generation, Amazon und HomePod Mini, Apple – Modell Classic Built-in (weiß)",
          lnk: "https://www.amazon.de/Splin-Eingebaute-Deckenhalterung-kompatibel-Generation/dp/B0BDZXNF83/ref=sr_1_12?dib=eyJ2IjoiMSJ9.VjLK3DMcuCEYU8s7zYbKwwNMp4f8d1D8BjReFd2no6xpqCQimATUUBE8uoqm6rY9yXYAxQQFFTMj2b6tN10R4g3SGOaAaQ88KgbBJc2ikfffPs3Qu4JFeHh-KInheyvLZias_OL3zHMkwLqKuusDnUc0u5PSgZ-u991IGlNJ-A2a5DwsdJlnMh_6DHogpmppkE6YlvXY0okiIaFTfEey47JfkDCquFkFw7O1Xsla2Ms.J1VDzBDZeK9hmlu6-ckC7hkb19fL9LMO1CDPup8P9RE&dib_tag=se&keywords=Apple+HomePod+mini+wei%C3%9F&qid=1720205605&sr=8-12",
          nmSegments: [
            "splin",
            "deckenhalterung",
            "für",
            "den",
            "einbau",
            "kompatibel",
            "mit",
            "smart",
            "lautsprechern",
            "alexa",
            "echo",
            "dot",
            "4.",
            "und",
            "5.",
            "generation",
            "amazon",
            "und",
            "homepod",
            "mini",
            "apple",
            "–",
            "modell",
            "classic",
            "built",
            "in",
            "(weiß)",
          ],
          prc: 36.43,
        },
        {
          vendor: "",
          nm: "Vebos Standfuß Homepod weiß EIN Paar - Kompatibel mit Apple Homepod",
          lnk: "https://www.amazon.de/sspa/click?ie=UTF8&spc=MTozMzc0ODcwMjc0MDk0ODI6MTcyMDIwNTYwNTpzcF9tdGY6MjAwNDA0MTY2Mjc3MDQ6OjA6Og&url=%2FVebos-Standfu%25C3%259F-Homepod-wei%25C3%259F-Paar%2Fdp%2FB07YCRYM3L%2Fref%3Dsr_1_13_sspa%3Fdib%3DeyJ2IjoiMSJ9.VjLK3DMcuCEYU8s7zYbKwwNMp4f8d1D8BjReFd2no6xpqCQimATUUBE8uoqm6rY9yXYAxQQFFTMj2b6tN10R4g3SGOaAaQ88KgbBJc2ikfffPs3Qu4JFeHh-KInheyvLZias_OL3zHMkwLqKuusDnUc0u5PSgZ-u991IGlNJ-A2a5DwsdJlnMh_6DHogpmppkE6YlvXY0okiIaFTfEey47JfkDCquFkFw7O1Xsla2Ms.J1VDzBDZeK9hmlu6-ckC7hkb19fL9LMO1CDPup8P9RE%26dib_tag%3Dse%26keywords%3DApple%2BHomePod%2Bmini%2Bwei%25C3%259F%26qid%3D1720205605%26sr%3D8-13-spons%26sp_csd%3Dd2lkZ2V0TmFtZT1zcF9tdGY%26psc%3D1",
          nmSegments: [
            "vebos",
            "standfuß",
            "homepod",
            "weiß",
            "ein",
            "paar",
            "kompatibel",
            "mit",
            "apple",
            "homepod",
          ],
          prc: 154.95,
        },
        {
          vendor: "",
          nm: "Wandhalterung kompatibel mit Homepod Mini, EWIGE Halterung für Home Pod Mini Ideal für Küche, Badezimmer Weiß",
          lnk: "https://www.amazon.de/Wandhalterung-kompatibel-EWIGE-Halterung-Badezimmer-Wei%C3%9F/dp/B0B4T3DVD3/ref=sr_1_14?dib=eyJ2IjoiMSJ9.VjLK3DMcuCEYU8s7zYbKwwNMp4f8d1D8BjReFd2no6xpqCQimATUUBE8uoqm6rY9yXYAxQQFFTMj2b6tN10R4g3SGOaAaQ88KgbBJc2ikfffPs3Qu4JFeHh-KInheyvLZias_OL3zHMkwLqKuusDnUc0u5PSgZ-u991IGlNJ-A2a5DwsdJlnMh_6DHogpmppkE6YlvXY0okiIaFTfEey47JfkDCquFkFw7O1Xsla2Ms.J1VDzBDZeK9hmlu6-ckC7hkb19fL9LMO1CDPup8P9RE&dib_tag=se&keywords=Apple+HomePod+mini+wei%C3%9F&qid=1720205605&sr=8-14",
          nmSegments: [
            "wandhalterung",
            "kompatibel",
            "mit",
            "homepod",
            "mini",
            "ewige",
            "halterung",
            "für",
            "home",
            "pod",
            "mini",
            "ideal",
            "für",
            "küche",
            "badezimmer",
            "weiß",
          ],
          prc: 10.08,
        },
        {
          vendor: "",
          nm: "Kompatibel mit Apple HomePod Mini Halter Wandhalterung Ständer Halterung mit integriertem Kabelmanagement,Lautsprecher Zubehör Rack,für Küche,Bad und Schlafzimmer (Apple HomePod Mini,Weiß)JP02Y",
          lnk: "https://www.amazon.de/Wandhalterung-integriertem-Kabelmanagement-Lautsprecher-Schlafzimmer/dp/B0B28BYR6B/ref=sr_1_15?dib=eyJ2IjoiMSJ9.VjLK3DMcuCEYU8s7zYbKwwNMp4f8d1D8BjReFd2no6xpqCQimATUUBE8uoqm6rY9yXYAxQQFFTMj2b6tN10R4g3SGOaAaQ88KgbBJc2ikfffPs3Qu4JFeHh-KInheyvLZias_OL3zHMkwLqKuusDnUc0u5PSgZ-u991IGlNJ-A2a5DwsdJlnMh_6DHogpmppkE6YlvXY0okiIaFTfEey47JfkDCquFkFw7O1Xsla2Ms.J1VDzBDZeK9hmlu6-ckC7hkb19fL9LMO1CDPup8P9RE&dib_tag=se&keywords=Apple+HomePod+mini+wei%C3%9F&qid=1720205605&sr=8-15",
          nmSegments: [
            "kompatibel",
            "mit",
            "apple",
            "homepod",
            "mini",
            "halter",
            "wandhalterung",
            "ständer",
            "halterung",
            "mit",
            "integriertem",
            "kabelmanagement",
            "lautsprecher",
            "zubehör",
            "rack",
            "für",
            "küche",
            "bad",
            "und",
            "schlafzimmer",
            "(apple",
            "homepod",
            "mini",
            "weiß)jp02y",
          ],
          prc: 19.99,
        },
        {
          vendor: "",
          nm: "SPORTLINK Kompatibel mit Homepod Mini Wandhalterung - Homepod Mini Halter Eingebautes Kabelmanagement Platzsparendes Design（2erPack-Weiß）",
          lnk: "https://www.amazon.de/SPORTLINK-Kompatibel-Homepod-Wandhalterung-Design%EF%BC%882erPack-Wei%C3%9F%EF%BC%89/dp/B09DYN79YB/ref=sr_1_16?dib=eyJ2IjoiMSJ9.VjLK3DMcuCEYU8s7zYbKwwNMp4f8d1D8BjReFd2no6xpqCQimATUUBE8uoqm6rY9yXYAxQQFFTMj2b6tN10R4g3SGOaAaQ88KgbBJc2ikfffPs3Qu4JFeHh-KInheyvLZias_OL3zHMkwLqKuusDnUc0u5PSgZ-u991IGlNJ-A2a5DwsdJlnMh_6DHogpmppkE6YlvXY0okiIaFTfEey47JfkDCquFkFw7O1Xsla2Ms.J1VDzBDZeK9hmlu6-ckC7hkb19fL9LMO1CDPup8P9RE&dib_tag=se&keywords=Apple+HomePod+mini+wei%C3%9F&qid=1720205605&sr=8-16",
          nmSegments: [
            "sportlink",
            "kompatibel",
            "mit",
            "homepod",
            "mini",
            "wandhalterung",
            "homepod",
            "mini",
            "halter",
            "eingebautes",
            "kabelmanagement",
            "platzsparendes",
            "design（2erpack",
            "weiß）",
          ],
          prc: 15.96,
        },
        {
          vendor: "",
          nm: "Real Wood Stand for homepod mini 2020,Tripod Accessories Protect Smart Speaker get Sound better, Secure Stable Wooden Mount Holder for home pod mini (white oak)",
          lnk: "https://www.amazon.de/homepod-Tripod-Accessories-Protect-Speaker-Wei%C3%9F/dp/B0CRR3DJJ5/ref=sr_1_17?dib=eyJ2IjoiMSJ9.VjLK3DMcuCEYU8s7zYbKwwNMp4f8d1D8BjReFd2no6xpqCQimATUUBE8uoqm6rY9yXYAxQQFFTMj2b6tN10R4g3SGOaAaQ88KgbBJc2ikfffPs3Qu4JFeHh-KInheyvLZias_OL3zHMkwLqKuusDnUc0u5PSgZ-u991IGlNJ-A2a5DwsdJlnMh_6DHogpmppkE6YlvXY0okiIaFTfEey47JfkDCquFkFw7O1Xsla2Ms.J1VDzBDZeK9hmlu6-ckC7hkb19fL9LMO1CDPup8P9RE&dib_tag=se&keywords=Apple+HomePod+mini+wei%C3%9F&qid=1720205605&sr=8-17",
          nmSegments: [
            "real",
            "wood",
            "stand",
            "for",
            "homepod",
            "mini",
            "2020",
            "tripod",
            "accessories",
            "protect",
            "smart",
            "speaker",
            "get",
            "sound",
            "better",
            "secure",
            "stable",
            "wooden",
            "mount",
            "holder",
            "for",
            "home",
            "pod",
            "mini",
            "(white",
            "oak)",
          ],
          prc: 16.8,
        },
        {
          vendor: "",
          nm: "Vebos Standfuß Homepod weiß - Kompatibel mit Apple Homepod",
          lnk: "https://www.amazon.de/sspa/click?ie=UTF8&spc=MTozMzc0ODcwMjc0MDk0ODI6MTcyMDIwNTYwNTpzcF9tdGY6MjAwNDA0MDMwMjA4MDQ6OjA6Og&url=%2FVebos-Standfu%25C3%259F-Homepod-wei%25C3%259F-Kompatibel%2Fdp%2FB07YCTHTBP%2Fref%3Dsr_1_18_sspa%3Fdib%3DeyJ2IjoiMSJ9.VjLK3DMcuCEYU8s7zYbKwwNMp4f8d1D8BjReFd2no6xpqCQimATUUBE8uoqm6rY9yXYAxQQFFTMj2b6tN10R4g3SGOaAaQ88KgbBJc2ikfffPs3Qu4JFeHh-KInheyvLZias_OL3zHMkwLqKuusDnUc0u5PSgZ-u991IGlNJ-A2a5DwsdJlnMh_6DHogpmppkE6YlvXY0okiIaFTfEey47JfkDCquFkFw7O1Xsla2Ms.J1VDzBDZeK9hmlu6-ckC7hkb19fL9LMO1CDPup8P9RE%26dib_tag%3Dse%26keywords%3DApple%2BHomePod%2Bmini%2Bwei%25C3%259F%26qid%3D1720205605%26sr%3D8-18-spons%26sp_csd%3Dd2lkZ2V0TmFtZT1zcF9tdGY%26psc%3D1",
          nmSegments: [
            "vebos",
            "standfuß",
            "homepod",
            "weiß",
            "kompatibel",
            "mit",
            "apple",
            "homepod",
          ],
          prc: 79.95,
        },
        {
          vendor: "",
          nm: "SX-Concept® - Homepod Wandhalterung | für Apple Homepod und Homepod 2 | optimale Raumoptik & platzsparend | Beweglich | Made in Germany weiß",
          lnk: "https://www.amazon.de/SX-Concept-Wandhalterung-Apple-HomePod-wei%C3%9F/dp/B07S3QXDCM/ref=sr_1_19?dib=eyJ2IjoiMSJ9.VjLK3DMcuCEYU8s7zYbKwwNMp4f8d1D8BjReFd2no6xpqCQimATUUBE8uoqm6rY9yXYAxQQFFTMj2b6tN10R4g3SGOaAaQ88KgbBJc2ikfffPs3Qu4JFeHh-KInheyvLZias_OL3zHMkwLqKuusDnUc0u5PSgZ-u991IGlNJ-A2a5DwsdJlnMh_6DHogpmppkE6YlvXY0okiIaFTfEey47JfkDCquFkFw7O1Xsla2Ms.J1VDzBDZeK9hmlu6-ckC7hkb19fL9LMO1CDPup8P9RE&dib_tag=se&keywords=Apple+HomePod+mini+wei%C3%9F&qid=1720205605&sr=8-19",
          nmSegments: [
            "sx",
            "concept®",
            "homepod",
            "wandhalterung",
            "|",
            "für",
            "apple",
            "homepod",
            "und",
            "homepod",
            "2",
            "|",
            "optimale",
            "raumoptik",
            "&",
            "platzsparend",
            "|",
            "beweglich",
            "|",
            "made",
            "in",
            "germany",
            "weiß",
          ],
          prc: 32.76,
        },
        {
          vendor: "",
          nm: "Aokicase Kompatibel mit Apple HomePod Mini Halter Wandhalterung Ständer Halterung Zubehör mit integriertem Kabelmanagement,Lautsprecher Zubehör Rack(Apple HomePod Mini,Weiß) 1 PCS",
          lnk: "https://www.amazon.de/Kompatibel-Wandhalterung-integriertem-Kabelmanagement-Lautsprecher/dp/B0B24Z8PS8/ref=sr_1_20?dib=eyJ2IjoiMSJ9.VjLK3DMcuCEYU8s7zYbKwwNMp4f8d1D8BjReFd2no6xpqCQimATUUBE8uoqm6rY9yXYAxQQFFTMj2b6tN10R4g3SGOaAaQ88KgbBJc2ikfffPs3Qu4JFeHh-KInheyvLZias_OL3zHMkwLqKuusDnUc0u5PSgZ-u991IGlNJ-A2a5DwsdJlnMh_6DHogpmppkE6YlvXY0okiIaFTfEey47JfkDCquFkFw7O1Xsla2Ms.J1VDzBDZeK9hmlu6-ckC7hkb19fL9LMO1CDPup8P9RE&dib_tag=se&keywords=Apple+HomePod+mini+wei%C3%9F&qid=1720205605&sr=8-20",
          nmSegments: [
            "aokicase",
            "kompatibel",
            "mit",
            "apple",
            "homepod",
            "mini",
            "halter",
            "wandhalterung",
            "ständer",
            "halterung",
            "zubehör",
            "mit",
            "integriertem",
            "kabelmanagement",
            "lautsprecher",
            "zubehör",
            "rack(apple",
            "homepod",
            "mini",
            "weiß)",
            "1",
            "pcs",
          ],
          prc: 20.99,
        },
        {
          vendor: "",
          nm: "KU XIU X40 Holzmaserung 3-in-1 Ladestation für Apple-Geräte, Ladestation für Apple Watch und iPhone, Mag-Safe Ladestation für iPhone 15/14/13/12 Serie, 5W Schnellladegerät für Apple Watch und AirPods",
          lnk: "https://www.amazon.de/sspa/click?ie=UTF8&spc=MTozMzc0ODcwMjc0MDk0ODI6MTcyMDIwNTYwNTpzcF9idGY6MzAwMTU3MjUzMjg4OTMyOjowOjo&url=%2FXIU-X40-Holzmaserung-Apple-Ger%25C3%25A4te-Schnellladeger%25C3%25A4t-X40-Brown%2Fdp%2FB0CSDNG5HL%2Fref%3Dsr_1_21_sspa%3Fdib%3DeyJ2IjoiMSJ9.VjLK3DMcuCEYU8s7zYbKwwNMp4f8d1D8BjReFd2no6xpqCQimATUUBE8uoqm6rY9yXYAxQQFFTMj2b6tN10R4g3SGOaAaQ88KgbBJc2ikfffPs3Qu4JFeHh-KInheyvLZias_OL3zHMkwLqKuusDnUc0u5PSgZ-u991IGlNJ-A2a5DwsdJlnMh_6DHogpmppkE6YlvXY0okiIaFTfEey47JfkDCquFkFw7O1Xsla2Ms.J1VDzBDZeK9hmlu6-ckC7hkb19fL9LMO1CDPup8P9RE%26dib_tag%3Dse%26keywords%3DApple%2BHomePod%2Bmini%2Bwei%25C3%259F%26qid%3D1720205605%26sr%3D8-21-spons%26sp_csd%3Dd2lkZ2V0TmFtZT1zcF9idGY%26psc%3D1",
          nmSegments: [
            "76.19999756160007 mm",
            "5 W",
            "ku",
            "xiu",
            "x40",
            "holzmaserung",
            "1",
            "ladestation",
            "für",
            "apple",
            "geräte",
            "ladestation",
            "für",
            "apple",
            "watch",
            "und",
            "iphone",
            "mag",
            "safe",
            "ladestation",
            "für",
            "iphone",
            "15",
            "14",
            "13",
            "12",
            "serie",
            "schnellladegerät",
            "für",
            "apple",
            "watch",
            "und",
            "airpods",
          ],
          prc: 67.22,
        },
        {
          vendor: "",
          nm: "PlusAcc Akku Kompatibel mit HomePod Mini - Batterie Ständer Home Pod Mini Zubehör Akkustation mit integriertem Kabelmanagement (Ohne Geräte) Schwarz",
          lnk: "https://www.amazon.de/sspa/click?ie=UTF8&spc=MTozMzc0ODcwMjc0MDk0ODI6MTcyMDIwNTYwNTpzcF9idGY6MzAwMDMwNjMxNjg4MDMyOjowOjo&url=%2FPlusAcc-Akku-Kompatibel-HomePod-Mini%2Fdp%2FB0BJNVJ5NR%2Fref%3Dsr_1_22_sspa%3Fdib%3DeyJ2IjoiMSJ9.VjLK3DMcuCEYU8s7zYbKwwNMp4f8d1D8BjReFd2no6xpqCQimATUUBE8uoqm6rY9yXYAxQQFFTMj2b6tN10R4g3SGOaAaQ88KgbBJc2ikfffPs3Qu4JFeHh-KInheyvLZias_OL3zHMkwLqKuusDnUc0u5PSgZ-u991IGlNJ-A2a5DwsdJlnMh_6DHogpmppkE6YlvXY0okiIaFTfEey47JfkDCquFkFw7O1Xsla2Ms.J1VDzBDZeK9hmlu6-ckC7hkb19fL9LMO1CDPup8P9RE%26dib_tag%3Dse%26keywords%3DApple%2BHomePod%2Bmini%2Bwei%25C3%259F%26qid%3D1720205605%26sr%3D8-22-spons%26sp_csd%3Dd2lkZ2V0TmFtZT1zcF9idGY%26psc%3D1",
          nmSegments: [
            "plusacc",
            "akku",
            "kompatibel",
            "mit",
            "homepod",
            "mini",
            "batterie",
            "ständer",
            "home",
            "pod",
            "mini",
            "zubehör",
            "akkustation",
            "mit",
            "integriertem",
            "kabelmanagement",
            "(ohne",
            "geräte)",
            "schwarz",
          ],
          prc: 45.37,
        },
      ],
    },
    dscrptnSegments: [""],
    eby_prop: "",
    esin: "",
    ean: "0190199720001",
    matched: true,
    matchedAt: "2024-07-05T18:53:29.490Z",
    nmSubSegments: [""],
    path: "hp_m_amazon",
    query: "Apple HomePod mini weiß",
    info_locked: false,
    info_taskId: "",
    cat_locked: false,
    cat_taskId: "",
    costs: {
      azn: 3.74,
      varc: 0,
      strg_1_hy: 0.02,
      strg_2_hy: 0.03,
      tpt: 3.12,
    },
    info_prop: "complete",
    cat_prop: "",
    ebyCategories: [
      {
        id: 14961,
        createdAt: "2024-07-21T11:45:54.152Z",
        category: "TV- & Heim-Audio-Zubehör",
      },
    ],
    a_qty: 1,
    e_qty: 1,
    qty: 1,
    uprc: 105,
    qty_batchId: "",
    qty_prop: "complete",
  };

  test(`TransformProduct`, () => {
    const {
      nm,
      lnk,
      info_locked,
      cat_locked,
      locked,
      description,
      nameSub,
      prc,
      promoPrice,
      mnfctr,
      vendor,
      ctgry,
      query,
      nmSubSegments,
      dscrptnSegments,
      eanList,
      candidates,
    } = transformProduct(oldProduct);
    expect(nm).toBe(oldProduct.name.replace(mnfctr, "").trim())
    expect(lnk).toBe(oldProduct.link)
    expect(info_locked).toBeUndefined()
    expect(cat_locked).toBeUndefined()
    expect(locked).toBeUndefined()
    expect(prc).toBe(oldProduct.promoPrice)
    expect(ctgry).toBe(oldProduct.category)
    expect(query).toBeUndefined()
    expect(nmSubSegments).toBeUndefined()
    expect(dscrptnSegments).toBeUndefined()
    expect(eanList[0]).toBe(oldProduct.ean)
    expect(candidates).toBeUndefined()
    expect(nameSub).toBeUndefined()
    expect(description).toBeUndefined()
    expect(vendor).toBeUndefined()
  });
});
